name: Build
on:
  push:
  pull_request:
  schedule:
    - cron: 26 8 4 * *

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        node_version:
          - 8
          - 10
    name: Node ${{ matrix.node_version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - run: >
          sudo apt -qy update;
          sudo apt -qy install libavahi-compat-libdnssd-dev
        if: matrix.os == 'ubuntu-latest'
      - run: npm install -g grunt-cli bower
      - run: npm install        # this also includes "grunt dist"
      - run: npm test
  docker:
    needs: build
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    name: Build Docker images
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: compute Docker tag name
        id: tagname
        run: |
          case ${GITHUB_REF} in
            refs/tags/v*)
              echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}
              ;;
            refs/heads/master)
              echo ::set-output name=tag::latest
              ;;
            *)
              echo ::set-output name=tag::${GITHUB_SHA}
              ;;
          esac
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/vincentbernat/dashkiosk:${{ steps.tagname.outputs.tag }}
